import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";


const Home: NextPage = () => {
  const router = useRouter();
<<<<<<< HEAD
  const handleclick = ()=>{
    router.push('/login');

  }
=======
const handleClick = () =>{
router.push('/login')
}
>>>>>>> f94d61a7c4153285e50124b2d2319b0ae986076d
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello World!!!</h1>
<<<<<<< HEAD
        <button className='bg-primary text-white' onClick={handleclick}>Login</button>
=======
        <button className='bg-success' onClick={handleClick }> Login </button>
>>>>>>> f94d61a7c4153285e50124b2d2319b0ae986076d
      </main>

      
    </div>
  )
}

export default Home
