import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";


const Home: NextPage = () => {
  const router = useRouter();
  const handleclick = ()=>{
    router.push('/login');

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello World!!!</h1>
        <button className='bg-primary text-white' onClick={handleclick}>Login</button>
      </main>

      
    </div>
  )
}

export default Home
